[platformio]
default_envs = genericSTM32H750VB

; custom common options
[env]
platform = ststm32
board = genericSTM32H750VB
framework = arduino
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
upload_speed = 256000 
monitor_speed = 115200
build_flags =
    -I include

[env:genericSTM32H750VB]
build_src_filter = +<main.cpp>